/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cookbook;


import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;

import cookbook.controller.MainController;
import javafx.application.Application;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.image.Image;
import javafx.stage.Stage;
import javafx.fxml.FXMLLoader;

public class Cookbook extends Application {

    @Override
    public void start(Stage primaryStage) throws Exception {
        Parent root = FXMLLoader.load(getClass().getClassLoader().getResource("animation_copy.fxml"));
        Scene scene = new Scene(root);
        Image icon = new Image(getClass().getResource("/images/Recipro logo white.png").toExternalForm());
        primaryStage.getIcons().add(icon);
        primaryStage.setTitle("RECIPRO");
        primaryStage.setScene(scene);
        primaryStage.show(); 
    }

}
